apiVersion: api.techsre.io/v1alpha1
kind: HPAReplicaSchedule
metadata:
  name: ppbl-pg-acquiring-biz-service
  namespace: prod
spec:
  hpaName: ppbl-pg-acquiring-biz-service
  namespace: prod
  schedules:
  - hour: 17
    maxReplicas: 12
    minReplicas: 4
    minute: 19
  - hour: 17
    maxReplicas: 10
    minReplicas: 1
    minute: 20