apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hpareplicaschedules.serviceAccountName" . }}
rules:
- apiGroups: [""]
  resources: ["pods", namespaces]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["api.techsre.io"]
  resources: ["hpareplicaschedules"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
