---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: {{ include "hpareplicaschedules.serviceAccountName" . }}
# subjects:
# - kind: ServiceAccount
#   name: {{ include "hpareplicaschedules.serviceAccountName" . }}
# roleRef:
#   kind: Role
#   name: {{ include "hpareplicaschedules.serviceAccountName" . }}
#   apiGroup: rbac.authorization.k8s.io

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hpareplicaschedules.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "hpareplicaschedules.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "hpareplicaschedules.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io