apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hpareplicaschedules.api.techsre.io
spec:
  group: api.techsre.io
  names:
    kind: HPAReplicaSchedule
    plural: hpareplicaschedules
    singular: hpareplicaschedule
    listKind: HPAReplicaScheduleList
    shortNames:
    - hpars
    - hrs
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: HPAReplicaSchedule is the Schema for the hpareplicaschedules API
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
              properties:
                name:
                  type: string
            spec:
              type: object
              properties:
                namespace:
                  type: string
                hpaName:
                  type: string
                schedules:
                  type: array
                  items:
                    type: object
                    properties:
                      hour:
                        type: integer   # Representing the hour of the schedule
                        minimum: 0
                        maximum: 23
                      minute:
                        type: integer   # Representing the minute of the schedule
                        minimum: 0
                        maximum: 59
                      minReplicas:
                        type: integer
                      maxReplicas:
                        type: integer
                      daysOfWeek:
                        type: string
                        default: "Mon-Sun"